//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rent()
        {
            this.item = new HashSet<item>();
        }
    
        public int rent_id { get; set; }
        public System.DateTime rent_start { get; set; }
        public System.DateTime rent_end { get; set; }
        public int user_account_id { get; set; }
        public bool isActive { get; set; }
    
        public virtual user_account user_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
    }
}
