//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_account()
        {
            this.recommendation = new HashSet<recommendation>();
            this.rent = new HashSet<rent>();
            this.vote = new HashSet<vote>();
        }

        public user_account(string username, string email, string firstName, string lastName, string password)
        {
            this.recommendation = new HashSet<recommendation>();
            this.rent = new HashSet<rent>();
            this.vote = new HashSet<vote>();
            this.username = username;
            this.email = email;
            this.first_name = firstName;
            this.last_name = lastName;
            this.user_type = "user";
            this.deleted = false;
            //password hash
            this.password = password;
        }

        public int user_account_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public bool deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recommendation> recommendation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> vote { get; set; }
    }
}
