//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote
    {
        public int vote_id { get; set; }
        public int user_accout_id { get; set; }
        public int recommendation_id { get; set; }
    
        public virtual recommendation recommendation { get; set; }
        public virtual user_account user_account { get; set; }
    }
}
